on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - run: |
        # Hack to get setup-python to work on act
        if [ ! -f "/etc/lsb-release" ] ; then
          echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
        fi

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install SDL
      run: sudo apt update && sudo apt install -y libsdl2-dev

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO tests
      run: make test
